### ISSUE TITLE
setExpectedCenter when setMapOrientation is not zero

### ISSUE THREAD

**Issue by PaoloDozio** [osmdroid/osmdroid#1348]
## Issue Type

[X] Question
[X] Bug
[ ] Improvement
[ ] Build system related
[ ] Performance
[ ] Documentation

## Description and/or steps/code to reproduce the problem

I don't know if it is a bug or a "feature" bug this is what happen.
What I want to do is a GPS tracker system where I have the map and on the map there is the route done and the actual position. I would like to rotate the map in order to have always the driving direction set to top of the screen.
For this I do.
```
mLastDriveDirection = (360 - location.getBearing());
                             
if (mLastDriveDirection < 0)
    mLastDriveDirection += 360;
if (mLastDriveDirection > 360)
    mLastDriveDirection -= 360;
mMapOSM.setMapOrientation(mLastDriveDirection);
```
and the map rotate correctly.
Now I would like also to set the position with an offset, I don't want to the driver position in the middle of the map, but in 1/3 of the screen in order to have more map in driving direction.
I hope I was clear in my description..

In order to do this I do
`mMapOSM.setExpectedCenter(gp, 0, mMapOSM.getHeight() / 6); `

Here you can see the arrow in the correct position

![image](https://user-images.githubusercontent.com/46484640/58344976-7b748880-7e57-11e9-84d7-b57bdef8039f.png)

The map is centered correctly but only if setMapOrientation is set to 0, otherwise also this offset is rotated and it is not what I want..

Here you can see the center of arrow rotated with map

![image](https://user-images.githubusercontent.com/46484640/58345199-153c3580-7e58-11e9-910a-96e35edcf4e9.png)

I tried also to use
`mMapOSM.setPadding(0,200,0,0);`
instead setExpectedCenter, but it doesn't work.. or I don't understand how it works..

Could you clarify what I need to do in order to do what I want?

Thanks in advance for your support.

### If it's a bug, version(s) of android this affects:

All

### Version of osmdroid the issue relates to:

6.1.0

**Comment by monsieurtanuki** [comment]
Duplicate with #1294.
I'll have a look in early June.

**Comment by PaoloDozio** [comment]
> Duplicate with #1294.
> I'll have a look in early June.

Thanks a lot and sorry for duplicated "issue"..

**Comment by monsieurtanuki** [comment]
@PaoloDozio Just PR'ed #1353 - feel free to test it.

**Comment by monsieurtanuki** [comment]
> When do you think this added feature will be available in the baseline?

@PaoloDozio Not before it has been tested by who created the issue ;)
I guess @pasniak will test it for #1294.

**Comment by PaoloDozio** [comment]
Sorry, I never used GIT and I'm using always the released version 6.1.0.
I never used the snapshot of the project.
In order to test the fixed issue, how can I do?
Thanks.

**Comment by monsieurtanuki** [comment]
If you ask me, I do it in a very lousy way: I download the java sources and integrate them into my project.

**Comment by monsieurtanuki** [comment]
Solved by #1353

**Comment by mminelli** [comment]
This old issue is close/solved but I still experience the wrong behavior explained by OP. Here is a snippet of my code:

```
        if (followMe) {
            float bearing = 20;  // just to test with a bearing != 0
            mapView.setMapOrientation(bearing);
            mapView.setExpectedCenter(currentLocation, 0, (long) (mapView.getHeight() / 2 * 0.7));
        }
```
Testing with the latest release v6.1.13 and it's exactly as in the picture where OP writes "the arrow should be here".

Am I doing something wrong?

**Comment by mminelli** [comment]
@monsieurtanuki  Please let me know if I should open a new issue. Initially I did not because the behavior I see seems to be exactly the same as described in this one.

**Comment by monsieurtanuki** [comment]
@mminelli Indeed, please create a brand new issue with details and a reference to the current one.

**Comment by mminelli** [comment]
@monsieurtanuki Thank you, I opened #1862 .
