### ISSUE TITLE
Cache problem

### ISSUE THREAD

**Issue by Rainexxx** [osmdroid/osmdroid#496]
Since I updated the version of library up to 5.4 (and 5.5) I started feeling pain in the ass, in other words there is a problem with caching!   
 The number of queries to the server has increased in 3 times! Can you even imagine? Ha? 
 There is no “EXPIRES” in headers’ response from the server,  so in this case it has to be alive for a week! BUTT, when I restart my app, the cache cleans up, despite that fact that the caching time set for a week! 
 And mainly, the same tiles are cleaned up and loaded! (again and again, the same, do you feel me bro?) 
 Where is the problem? It feels like I am loosing my mind, my head has been aching since that time, I barely can eat, walk and sleep! Is there a solution? What should I do? How am I supposed to live now?

**Comment by spyhunter99** [comment]
Try 5.6. That issue should be fixed

**Comment by Rainexxx** [comment]
Tried 5.6, but it did not solve my problems. First start app, tiles inserted into the database. All tiles cache time is set for the week. After restart app, removed some tiles in the cache and loaded from the network. Why tiles are removed? When used by the file cache, that such problems were not.

**Comment by spyhunter99** [comment]
They should only be removed if the total cache size is greater than the
configured trim cache size,which is 500mb by default. And at that, it will
only delete the oldest tiles.

**Comment by Rainexxx** [comment]
Error is associated not only with cache, and with all providers. Provider selection algorithm does not work properly. Example with default settings. If **mPending** has 40 entries, **mWorking** has maximum size 8 entries (equals ThreadPoolSize), and 32 entries waiting for execute in the ExecuterService. So, if put one more entry in **mPending** (size > 40), then removeEldestEntry executed, removed entry and give control to the next provider, without waiting for the result of the current provider. If the current provider **MapTileSqlCacheProvider**, then skipped some tiles and downloaded from the server. If enable debug mode tile provider then the problem is not noticeable. You can repeat error, add Thread.sleep(1000) to the **MapTileSqlCacheProvider.TileLoader.loadTile(...)** and set **tileFileSystemMaxQueueSize** less than size tiles load to display. Thus, one provider can't simultaneously load more than set size in  **tileFileSystemMaxQueueSize** or **tileDownloadMaxQueueSize**. It's not right.

**Comment by spyhunter99** [comment]
whoa great find. any suggestion on how to fix it?

**Comment by spyhunter99** [comment]
#464 related

**Comment by spyhunter99** [comment]
@Rainexxx is this mitigated by the now adjustable thread pool sizes and adjustable queue sizes? After I increased the queue size and added the additional sleep statement that you described, i had no problems loading stuff from the sql cache. So now that it's adjustable via the the configuration class, it should be easy to overcome. We could remove the limits on the queue size but i would imagine that it's there for a reason

**Comment by spyhunter99** [comment]
I played around with the settings, increasing the queue size appears to have fixed it, even with the huge delays. Please test on 5.6.2 and report back

**Comment by spyhunter99** [comment]
closing for now, comment back or reopen if it's still an issue after upgrading
