### ISSUE TITLE
ScrollableAreaLimit Wraps

### ISSUE THREAD

**Issue by Maradox** [osmdroid/osmdroid#645]
When using `setScrollableAreaLimit` the scroll sometime wraps.

**Scroll:**
For example a boundings-box which has the left bound at `0px`. When I scroll left, the scroll wraps to the right side instead of staying at 0. Reason being that before the bounding-box check, the `world_size` is added until `x>=0`.

**Zoom:**
When zooming in on the edges - on releasing the fingers:
* It wraps to the other side.
* Or for example when zooming in on the right side, it zooms in a bit farther left.

Version: 5.6.5

**Comment by Maradox** [comment]
It seems to me that one reason for the zoom behavior is that `mTargetZoomLevel` is no longer set in the `MapView`. Thus the bounding box uses the old zoom during the zoom and restricts the area more than it should

**Comment by spyhunter99** [comment]
great work, please update this ticket if you feel you have a solution to this or open a pr

**Comment by spyhunter99** [comment]
I just checked the history for MapView and the variable for `mTargetZoomLevel`  hasn't been set since at least 2014. Did this problem occur on older versions of osmdroid?

**Comment by Maradox** [comment]
Until now I used osmdroid 4.1, which also had some of these problems, but could be solved with a workardound. I didn't switch to a newer osmdroid version until now due to these problems since the old workaround does not work anymore.

I was able to fix all the mentioned problems but zoom via pinch near borders. If I`m able to fix this as well, I will create a PR.

**Comment by spyhunter99** [comment]
I'd suggest you merge master into whatever branch you're working on. I
think #640 may have affected this with the floating point zoom

**Comment by Maradox** [comment]
I'm currently trying to incorporate the bounding-box during the pinch-zoom itself, so the boundings are respected and you cannot zoom-scroll beyond them. 

However, I'm not sure how to check the coordinates from `scrollTo` against the bounding box, since during a pinch-zoom the x and y parameters of `scrollTo` are somewhat strange. The x/y coordinates vary for the same viewport of a map - dependent on from which location the zoom started. I think I have to use `mMultitouchScale`, but I'm not sure how exactly.

Any ideas on how to check the x/y coordinates from `scrollTo` against a bounding-box during the pinch-zoom (where `mMultitouchScale != 1)`? For other scrolling szenarios and double-tab zoom the bounding-check already works for me.

**Comment by monsieurtanuki** [comment]
@Maradox I believe it's fixed now, isn't it?

**Comment by Maradox** [comment]
Most of it yes. The zoom near the bounding-box still does not work, though there is an issue for it: https://github.com/osmdroid/osmdroid/issues/762
